# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L32
seed: 42
# epoch * n_steps * nenvs: 500×512*8*8
n_timesteps: 500000
n_steps_per_update: 152
n_minibatches: 40

policy: 'MlpPolicy'
learning_rate: !!float 5e-5
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
normalize_advantage: True
ent_coef: 0

policy_kwargs: "dict(
                  ortho_init=True,
                  activation_fn=nn.Tanh,
                  net_arch=[512, 512],
                )"

# Uses VecNormalize class to normalize obs
normalize_input: True
clip_obs: 10.0
# Uses VecNormalize class to normalize rew
normalize_value: True
clip_rew: 10.0
